#!/usr/bin/env node
/**
 * Interactive setup: creates/updates .env with Google OAuth credentials.
 * Run: npm run setup:google
 */
import fs from "fs";
import path from "path";
import readline from "readline";
import { fileURLToPath } from "url";
import crypto from "crypto";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const envPath = path.join(root, ".env");
const examplePath = path.join(root, ".env.example");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question) {
  return new Promise((resolve) => rl.question(question, resolve));
}

function parseEnv(content) {
  const vars = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    vars[key] = val;
  }
  return vars;
}

function serializeEnv(vars, comments) {
  const lines = [...comments, ""];
  const order = [
    "PORT",
    "JWT_SECRET",
    "FRONTEND_URL",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "GOOGLE_REDIRECT_URI",
  ];
  const written = new Set();
  for (const key of order) {
    if (vars[key] !== undefined) {
      lines.push(`${key}=${vars[key]}`);
      written.add(key);
    }
  }
  for (const [key, val] of Object.entries(vars)) {
    if (!written.has(key)) lines.push(`${key}=${val}`);
  }
  return lines.join("\n").trim() + "\n";
}

async function main() {
  console.log("\n  Daily Tracker — Google OAuth setup\n");
  console.log("  1. Open: https://console.cloud.google.com/apis/credentials");
  console.log("  2. Create OAuth client ID → Web application");
  console.log("  3. Authorized redirect URI (required):\n");
  console.log("     http://localhost:3001/api/auth/google/callback\n");

  let vars = {};
  if (fs.existsSync(envPath)) {
    vars = parseEnv(fs.readFileSync(envPath, "utf8"));
    console.log("  Found existing .env — press Enter to keep current values.\n");
  } else if (fs.existsSync(examplePath)) {
    vars = parseEnv(fs.readFileSync(examplePath, "utf8"));
    console.log("  Creating .env from .env.example\n");
  }

  const clientId =
    (await ask(
      `  GOOGLE_CLIENT_ID${vars.GOOGLE_CLIENT_ID ? ` [${vars.GOOGLE_CLIENT_ID}]` : ""}: `,
    )).trim() || vars.GOOGLE_CLIENT_ID;

  const clientSecret =
    (await ask(
      `  GOOGLE_CLIENT_SECRET${vars.GOOGLE_CLIENT_SECRET ? " [hidden]" : ""}: `,
    )).trim() || vars.GOOGLE_CLIENT_SECRET;

  const frontend =
    (await ask(
      `  FRONTEND_URL (Vite)${vars.FRONTEND_URL ? ` [${vars.FRONTEND_URL}]` : " [http://localhost:5173]"}: `,
    )).trim() ||
    vars.FRONTEND_URL ||
    "http://localhost:5173";

  const redirect =
    (await ask(
      `  GOOGLE_REDIRECT_URI${vars.GOOGLE_REDIRECT_URI ? ` [${vars.GOOGLE_REDIRECT_URI}]` : ""}: `,
    )).trim() ||
    vars.GOOGLE_REDIRECT_URI ||
    "http://localhost:3001/api/auth/google/callback";

  if (!clientId || clientId.includes("your-client")) {
    console.error("\n  Error: A real GOOGLE_CLIENT_ID is required.\n");
    process.exit(1);
  }
  if (!clientSecret || clientSecret.includes("your-client-secret")) {
    console.error("\n  Error: A real GOOGLE_CLIENT_SECRET is required.\n");
    process.exit(1);
  }

  const jwt =
    vars.JWT_SECRET && !vars.JWT_SECRET.startsWith("change-this")
      ? vars.JWT_SECRET
      : crypto.randomBytes(32).toString("hex");

  const out = serializeEnv(
    {
      PORT: vars.PORT || "3001",
      JWT_SECRET: jwt,
      FRONTEND_URL: frontend,
      GOOGLE_CLIENT_ID: clientId,
      GOOGLE_CLIENT_SECRET: clientSecret,
      GOOGLE_REDIRECT_URI: redirect,
    },
    [
      "# Daily Tracker — generated by npm run setup:google",
      "# Google OAuth: https://console.cloud.google.com/apis/credentials",
    ],
  );

  fs.writeFileSync(envPath, out, "utf8");
  rl.close();

  console.log("\n  ✓ Wrote .env");
  console.log("\n  Next steps:");
  console.log("    1. In Google Cloud Console, confirm redirect URI:");
  console.log(`       ${redirect}`);
  console.log("    2. Restart the app:  npm run dev");
  console.log(`    3. Open ${frontend}/login and click Continue with Google\n`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
